# Effective op time analysis

In [1]:
import os
import csv
import pandas as pd
import plotly.express as px

with open("../Data and descriptions/Case Rigshospitalet - Cancelled operations.csv", newline="", encoding="utf-8") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['Case-ID Anonymous;Dato og tid;Primær procedure - Tekst;Aflyst efter operationsprogrammet er afsluttet?;"Aflyst på dagen for operationen? ";Aflysningsårsag;Forventet varighed (min.);Ombooket;Stue;Operationsgang ID']
['7574;2024-01-03 22:05:00', '000;"GASTROSKOPI";"Nej";"Nej";"";93;"Nej";"CKO LEJE 01";"618"']
['7868;2024-01-05 20:50:00', '000;"KOLOSKOPI";"Nej";"Nej";"";87;"Nej";"CKO LEJE 03";"618"']
['8054;2024-01-07 14:10:00', '000;"INVR EMBOLISERING";"Nej";"Nej";"";132;"Nej";"CKO RTG LEJE U/A";"618"']
['11481;2024-01-26 11:00:00', '000;"INVR EMBOLISERING";"Nej";"Nej";"";207;"Nej";"CKO RTG LEJE 14";"618"']
['16394;2024-02-26 08:05:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";111;"Nej";"CKO RTG LEJE 11";"618"']
['19035;2024-03-11 02:20:00', '000;"GASTROSKOPI";"Nej";"Nej";"";92;"Nej";"CKO LEJE 01";"618"']
['26827;2024-04-26 12:00:00', '000;"RESEKTION TYNDTARM";"Nej";"Nej";"";215;"Nej";"CKO LEJE 02";"618"']
['27141;2024-04-27 11:00:00', '000;"INVR PTC/DRÆNAGE";"Nej";"Nej";"";126;"Nej";"CKO RTG LEJE U/A";"618"']
['27146;2024-05-01 09:00:00', '000;"INVR PTC/DRÆNAGE";"Nej";"Nej";"";139;"Nej";"CKO RTG LEJE U/A";"618"']
['27372;2024-04-29 20:00:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";100;"Nej";"CKO LEJE 04";"618"']
['27492;2024-04-30 07:50:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";116;"Nej";"CKO RTG LEJE 11";"618"']
['28648;2024-05-07 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";112;"Nej";"CKO RTG LEJE 12";"618"']
['29178;2024-05-10 09:30:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";86;"Nej";"CKO RTG LEJE 12";"618"']
['29340;2024-05-12 14:00:00', '000;"GASTROSKOPI";"Nej";"Nej";"";95;"Nej";"CKO LEJE 01";"618"']
['29602;2024-05-14 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";120;"Nej";"CKO RTG LEJE 11";"618"']
['29726;2024-05-29 13:15:00', '000;"ANTEGRAD STENTNING";"Nej";"Nej";"";93;"Nej";"CKO LEJE 03";"618"']
['31553;2024-05-23 18:00:00', '000;"GASTROSKOPI";"Nej";"Nej";"";97;"Nej";"CKO LEJE 01";"618"']
['31942;2024-05-27 11:00:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";106;"Nej";"CKO RTG LEJE 11";"618"']
['32114;2024-05-28 09:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";133;"Nej";"CKO RTG LEJE 11";"618"']
['32344;2024-05-29 11:00:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";96;"Nej";"CKO RTG LEJE 12";"618"']
['32721;2024-05-30 12:30:00', '000;"INVR EMBOLISERING";"Nej";"Nej";"";187;"Nej";"CKO RTG LEJE 12";"618"']
['33348;2024-06-04 08:06:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";119;"Nej";"CKO RTG LEJE 11";"618"']
['33530;2024-06-07 08:05:00', '000;"NEOIMPLANTATION AF URETER";"Nej";"Nej";"";305;"Nej";"CKO LEJE 17";"618"']
['33831;2024-06-10 12:20:00', '000;"ANTEGRAD STENTNING";"Nej";"Nej";"";99;"Nej";"CKO LEJE 17";"618"']
['33993;2024-06-25 08:05:00', '000;"ANLÆGGELSE AF P-RØR";"Nej";"Nej";"";102;"Nej";"CKO LEJE 05";"618"']
['34513;2024-06-10 16:05:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";137;"Nej";"CKO LEJE 04";"618"']
['34685;2024-06-11 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";115;"Nej";"CKO RTG LEJE 12";"618"']
['35072;2024-06-17 12:30:00', '000;"RESEKTION AF VENTRIKEL";"Nej";"Nej";"";288;"Nej";"CKO LEJE 01";"618"']
['35245;2024-06-13 09:00:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";141;"Nej";"CKO RTG LEJE 12";"618"']
['35698;2024-06-14 21:30:00', '000;"KOLEKTOMI - TOTAL";"Nej";"Nej";"";211;"Nej";"CKO LEJE 01";"618"']
['36024;2024-06-18 09:15:00', '000;"GASTROSKOPI";"Nej";"Nej";"";90;"Nej";"CKO LEJE 03";"618"']
['36026;2024-06-18 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";118;"Nej";"CKO RTG LEJE 12";"618"']
['36575;2024-06-20 13:55:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";137;"Nej";"CKO RTG LEJE 11";"618"']
['36690;2024-06-21 08:12:00', '000;"AV FISTEL KIRURGISK REVISION";"Nej";"Nej";"";203;"Nej";"CKO LEJE 08 (H)";"618"']
['37378;2024-06-25 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";119;"Nej";"CKO RTG LEJE 11";"618"']
['38053;2024-06-28 07:57:00', '000;"INVR TIPS";"Nej";"Nej";"";177;"Nej";"CKO RTG LEJE U/A";"618"']
['38259;2025-02-07 15:55:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";93;"Nej";"CKO RTG LEJE 11";"618"']
['38299;2024-07-23 08:05:00', '000;"ANLÆGGELSE AF P-RØR";"Nej";"Nej";"";101;"Nej";"CKO LEJE 05";"618"']
['38902;2024-07-03 10:45:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";137;"Nej";"CKO RTG LEJE 11";"618"']
['39728;2024-07-08 16:20:00', '000;"EKSPLORATIV LAPAROTOMI";"Nej";"Nej";"";101;"Nej";"CKO LEJE 01";"618"']
['39767;2024-07-09 11:18:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";162;"Nej";"CKO RTG LEJE 14";"618"']
['40667;2024-07-17 12:00:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";153;"Nej";"CKO RTG LEJE 11";"618"']
['40898;2024-07-17 18:35:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";89;"Nej";"CKO LEJE 03";"618"']
['40920;2024-07-18 08:00:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";140;"Nej";"CKO RTG LEJE 14";"618"']
['41640;2024-07-25 08:05:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";162;"Nej";"CKO RTG LEJE 14";"618"']
['41665;2024-07-26 16:35:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";89;"Nej";"CKO LEJE 04";"618"']
['41695;2024-07-26 11:10:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";96;"Nej";"CKO LEJE 04";"618"']
['42315;2024-07-31 08:29:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";104;"Nej";"CKO LEJE 04";"618"']
['43182;2024-08-07 08:30:00', '000;"INVR EMBOLISERING";"Nej";"Nej";"";146;"Nej";"CKO RTG LEJE U/A";"618"']
['44159;2024-08-13 16:10:00', '000;"EKSPLORATIV LAPAROTOMI";"Nej";"Nej";"";175;"Nej";"CKO LEJE 03";"618"']
['44303;2024-08-14 19:10:00', '000;"NYRETRANSPLANTATION";"Nej";"Nej";"";301;"Nej";"CKO LEJE 03";"618"']
['44698;2024-08-16 13:30:00', '000;"GASTROSKOPI";"Nej";"Nej";"";90;"Nej";"CKO LEJE 03";"618"']
['44840;2024-08-16 22:25:00', '000;"SÅRSKIFT";"Nej";"Nej";"";103;"Nej";"CKO LEJE 02";"618"']
['44854;2024-08-17 15:35:00', '000;"SÅRSKIFT";"Nej";"Nej";"";103;"Nej";"CKO LEJE 02";"618"']
['44862;2024-08-18 14:25:00', '000;"SÅRSKIFT";"Nej";"Nej";"";103;"Nej";"CKO LEJE 02";"618"']
['44880;2024-08-18 18:10:00', '000;"REOPERATION ABDOMINALKIRURGI - FASCIERUPTUR";"Nej";"Nej";"";116;"Nej";"CKO LEJE 02";"618"']
['44889;2024-08-21 17:15:00', '000;"REVISION AF CICATRICE";"Nej";"Nej";"";81;"Nej";"CKO LEJE 02";"618"']
['45149;2024-08-20 08:00:00', '000;"INVR DIAGNOSTISK ANGIOGRAFI/FLEBOGRAFI";"Nej";"Nej";"";107;"Nej";"CKO RTG LEJE 12";"618"']
['45374;2024-08-20 17:10:00', '000;"GASTROSKOPI";"Nej";"Nej";"";85;"Nej";"CKO LEJE 01";"618"']
['45388;2024-08-21 10:00:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";83;"Nej";"CKO RTG LEJE 12";"618"']
['45624;2024-08-23 18:00:00', '000;"SÅRSKIFT";"Nej";"Nej";"";102;"Nej";"CKO LEJE 02";"618"']
['45635;2024-08-22 11:45:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";84;"Nej";"CKO RTG LEJE 12";"618"']
['46124;2024-08-26 08:20:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";135;"Nej";"CKO RTG LEJE 12";"618"']
['46129;2024-08-26 08:05:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";100;"Nej";"CKO RTG LEJE 11";"618"']
['46151;2024-08-26 11:00:00', '000;"INVR EMBOLISERING";"Nej";"Nej";"";167;"Nej";"CKO RTG LEJE U/A";"618"']
['46377;2024-08-27 08:02:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";133;"Nej";"CKO RTG LEJE 11";"618"']
['46963;2024-08-29 11:55:00', '000;"INVR VENOGRAFI THORAX";"Nej";"Nej";"";154;"Nej";"CKO RTG LEJE 12";"618"']
['47386;2024-09-02 08:40:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";103;"Nej";"CKO RTG LEJE U/A";"618"']
['47595;2024-09-03 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";116;"Nej";"CKO RTG LEJE 11";"618"']
['47612;2024-09-03 09:40:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";116;"Nej";"CKO RTG LEJE 12";"618"']
['47845;2024-09-04 10:40:00', '000;"RESEKTION AF COLON";"Nej";"Nej";"";175;"Nej";"CKO LEJE 02";"618"']
['48373;2024-09-06 14:00:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";96;"Nej";"CKO LEJE 03";"618"']
['48778;2024-09-10 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";145;"Nej";"CKO RTG LEJE 11";"618"']
['49452;2024-09-12 21:30:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";98;"Nej";"CKO LEJE 03";"618"']
['50071;2024-09-17 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";114;"Nej";"CKO RTG LEJE 11";"618"']
['50841;2024-09-20 15:30:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";138;"Nej";"CKO RTG LEJE 11";"618"']
['51221;2024-09-24 08:05:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";114;"Nej";"CKO RTG LEJE 11";"618"']
['52447;2024-10-01 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";114;"Nej";"CKO RTG LEJE 12";"618"']
['52448;2024-10-01 10:10:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";114;"Nej";"CKO RTG LEJE 12";"618"']
['52913;2024-10-02 21:05:00', '000;"GASTROSKOPI";"Nej";"Nej";"";28;"Nej";"CKO LEJE 01";"618"']
['53416;2024-10-07 12:30:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";89;"Nej";"CKO RTG LEJE 14";"618"']
['54767;2024-10-15 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";114;"Nej";"CKO RTG LEJE 11";"618"']
['54975;2024-10-16 10:35:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";138;"Nej";"CKO RTG LEJE 11";"618"']
['55117;2024-10-17 08:10:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";137;"Nej";"CKO RTG LEJE 11";"618"']
['55743;2024-10-22 08:10:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";115;"Nej";"CKO RTG LEJE 12";"618"']
['56567;2024-10-25 16:05:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";93;"Nej";"CKO LEJE 04";"618"']
['56890;2024-10-29 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";117;"Nej";"CKO RTG LEJE 11";"618"']
['57139;2024-10-31 09:00:00', '000;"REOPERATION ABDOMINALKIRURGI - SÅRRUPTUR";"Nej";"Nej";"";109;"Nej";"CKO LEJE 02";"618"']
['58059;2024-11-05 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";135;"Nej";"CKO RTG LEJE 11";"618"']
['58066;2024-11-05 11:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";117;"Nej";"CKO RTG LEJE 11";"618"']
['58735;2024-11-08 13:05:00', '000;"NEFROSTOMI";"Nej";"Nej";"";52;"Nej";"CKO LEJE 02";"618"']
['58824;2024-11-08 15:40:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";104;"Nej";"CKO LEJE 03";"618"']
['59252;2024-11-12 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";113;"Nej";"CKO RTG LEJE 12";"618"']
['60300;2024-11-18 08:00:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";140;"Nej";"CKO RTG LEJE 11";"618"']
['60541;2024-11-19 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";115;"Nej";"CKO RTG LEJE 11";"618"']
['61040;2024-11-20 21:10:00', '000;"EKSPLORATIV LAPAROTOMI";"Nej";"Nej";"";202;"Nej";"CKO LEJE 16";"618"']
['61535;2024-11-25 08:15:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";115;"Nej";"CKO RTG LEJE 11";"618"']
['61761;2024-11-26 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";115;"Nej";"CKO RTG LEJE 12";"618"']
['62240;2024-11-27 19:35:00', '000;"KOLOSKOPI";"Nej";"Nej";"";99;"Nej";"CKO LEJE 01";"618"']
['63002;2024-12-03 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";112;"Nej";"CKO RTG LEJE 12";"618"']
['63003;2024-12-03 09:52:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";112;"Nej";"CKO RTG LEJE 12";"618"']
['63632;2024-12-05 19:05:00', '000;"GASTROSKOPI";"Nej";"Nej";"";22;"Nej";"CKO LEJE 02";"618"']
['63918;2024-12-08 09:05:00', '000;"INVR PTC/DRÆNAGE";"Nej";"Nej";"";174;"Nej";"CKO RTG LEJE U/A";"618"']
['64018;2024-12-08 21:10:00', '000;"GASTROSKOPI";"Nej";"Nej";"";78;"Nej";"CKO LEJE 01";"618"']
['64088;2024-12-09 11:56:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";137;"Nej";"CKO RTG LEJE 11";"618"']
['64266;2024-12-10 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";115;"Nej";"CKO RTG LEJE 11";"618"']
['64627;2024-12-11 13:05:00', '000;"NEFROSTOMI";"Nej";"Nej";"";76;"Nej";"CKO LEJE 04";"618"']
['65450;2024-12-17 08:00:00', '000;"INVR DIAGNOSTISK ANGIOGRAFI/FLEBOGRAFI";"Nej";"Nej";"";111;"Nej";"CKO RTG LEJE 11";"618"']
['65466;2024-12-17 10:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";115;"Nej";"CKO RTG LEJE 11";"618"']
['66391;2024-12-27 08:00:00', '000;"LAPAROSKOPISK NEFREKTOMI";"Nej";"Nej";"";257;"Nej";"CKO LEJE 17";"618"']
['66908;2024-12-30 07:40:00', '000;"INVR ANGIOGRAFI UE";"Nej";"Nej";"";145;"Nej";"CKO RTG LEJE 14";"618"']
['67066;2025-01-01 11:05:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";97;"Nej";"CKO RTG LEJE 14";"618"']
['67795;2025-01-06 22:30:00', '000;"INVR PTC/DRÆNAGE";"Nej";"Nej";"";314;"Nej";"CKO RTG LEJE 11";"618"']
['67801;2025-01-07 08:00:00', '000;"INVR DIAGNOSTISK ANGIOGRAFI/FLEBOGRAFI";"Nej";"Nej";"";112;"Nej";"CKO RTG LEJE 12";"618"']
['67842;2025-01-07 10:45:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";113;"Nej";"CKO RTG LEJE 12";"618"']
['68038;2025-01-09 09:00:00', '000;"GASTROSTOMI OG PEG";"Nej";"Nej";"";105;"Nej";"CKO LEJE 02";"618"']
['69120;2025-01-14 08:00:00', '000;"INVR BLODPRØVETAGNING";"Nej";"Nej";"";114;"Nej";"CKO RTG LEJE 11";"618"']
['69212;2025-01-20 13:00:00', '000;"ANTEGRAD STENTNING";"Nej";"Nej";"";103;"Nej";"CKO LEJE 04";"618"']
['69346;2025-01-14 20:10:00', '000;"LAPAROSKOPI - DIAGNOSTISK";"Nej";"Nej";"";86;"Nej";"CKO LEJE 01";"618"']
['70933;2025-01-22 17:45:00', '000;"NEFROSTOMI";"Nej";"Nej";"";55;"Nej";"CKO LEJE 03";"618"']
['72404;2025-01-31 08:05:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";159;"Nej";"CKO RTG LEJE 12";"618"']
['73442;2025-02-06 12:45:00', '000;"FREMLÆGNING AF COLON";"Nej";"Nej";"";179;"Nej";"CKO LEJE 01";"618"']
['74516;2025-02-12 15:20:00', '000;"TERAPEUTISK ØVRE SKOPI (GI)";"Nej";"Nej";"";147;"Nej";"CKO LEJE 01";"618"']
['74906;2025-02-15 18:55:00', '000;"LAPAROSKOPISK HERNIA INGUINALIS";"Nej";"Nej";"";89;"Nej";"CKO LEJE 01";"618"']
['76103;2025-02-23 09:00:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";86;"Nej";"CKO LEJE 04";"618"']
['77618;2025-03-04 12:05:00', '000;"LAPAROSKOPI - DIAGNOSTISK";"Nej";"Nej";"";117;"Nej";"CKO LEJE 01";"618"']
['78510;2025-03-08 12:35:00', '000;"KOLOSKOPI";"Nej";"Nej";"";108;"Nej";"CKO LEJE 01";"618"']
['78513;2025-03-08 16:00:00', '000;"NEFROSTOMI";"Nej";"Nej";"";59;"Nej";"CKO LEJE 03";"618"']
['78602;2025-03-10 10:17:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";112;"Nej";"CKO RTG LEJE 14";"618"']
['78779;2025-03-10 19:35:00', '000;"EKSPLORATIV LAPAROTOMI";"Nej";"Nej";"";195;"Nej";"CKO LEJE 03";"618"']
['79788;2025-03-17 03:05:00', '000;"EKSPLORATIV LAPAROTOMI";"Nej";"Nej";"";209;"Nej";"CKO LEJE 02";"618"']
['80027;2025-03-17 22:20:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";97;"Nej";"CKO LEJE 04";"618"']
['80562;2025-03-20 08:53:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";107;"Nej";"CKO RTG LEJE 14";"618"']
['81042;2025-03-22 15:05:00', '000;"ANASTOMOSEINSUFFICIENS";"Nej";"Nej";"";112;"Nej";"CKO LEJE 02";"618"']
['81075;2025-03-23 17:05:00', '000;"NEFROSTOMI";"Nej";"Nej";"";63;"Nej";"CKO LEJE 03";"618"']
['81085;2025-03-24 08:10:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";104;"Nej";"CKO RTG LEJE 11";"618"']
['81179;2025-03-24 10:29:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";104;"Nej";"CKO RTG LEJE 11";"618"']
['81347;2025-03-25 17:35:00', '000;"REOPERATION PGA. INFEKTIONER', ' BLØDNING', ' SÅRRUPTUR', 'LÆKAGE MM";"Nej";"Nej";"";134;"Nej";"CKO LEJE 03";"618"']
['82867;2025-04-02 11:35:00', '000;"AV FISTEL KIRURGISK REVISION";"Nej";"Nej";"";195;"Nej";"CKO LEJE 08 (H)";"618"']
['83114;2025-04-03 14:50:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";88;"Nej";"CKO LEJE 03";"618"']
['84010;2025-04-09 11:50:00', '000;"EKSPLORATIV LAPAROTOMI";"Nej";"Nej";"";192;"Nej";"CKO LEJE 21";"618"']
['84623;2025-04-10 19:05:00', '000;"NEFROSTOMI";"Nej";"Nej";"";59;"Nej";"CKO LEJE 03";"618"']
['84815;2025-04-12 09:00:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";87;"Nej";"CKO LEJE 04";"618"']
['86408;2025-04-25 10:35:00', '000;"REOPERATION PGA. INFEKTIONER', ' BLØDNING', ' SÅRRUPTUR', 'LÆKAGE MM";"Nej";"Nej";"";134;"Nej";"CKO LEJE 21";"618"']
['87420;2025-05-01 10:21:00', '000;"GASTROSKOPI";"Nej";"Nej";"";92;"Nej";"CKO LEJE 01";"618"']
['87714;2025-05-05 08:05:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";94;"Nej";"CKO RTG LEJE 11";"618"']
['87976;2025-05-05 18:00:00', '000;"NEFROSTOMI";"Nej";"Nej";"";62;"Nej";"CKO LEJE 03";"618"']
['89057;2025-05-12 08:40:00', '000;"INVR EMBOLISERING";"Nej";"Nej";"";161;"Nej";"CKO RTG LEJE 12";"618"']
['89908;2025-05-15 14:15:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";95;"Nej";"CKO RTG LEJE 11";"618"']
['90959;2025-05-24 09:00:00', '000;"TERAPEUTISK ØVRE SKOPI (GI)";"Nej";"Nej";"";92;"Nej";"CKO LEJE 01";"618"']
['91494;2025-05-26 08:10:00', '000;"INVR SCLEROSERING";"Nej";"Nej";"";86;"Nej";"CKO RTG LEJE 12";"618"']
['91613;2025-05-27 09:56:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";80;"Nej";"CKO RTG LEJE 12";"618"']
['92322;2025-05-29 21:55:00', '000;"EKSPLORATIV LAPAROTOMI";"Nej";"Nej";"";212;"Nej";"CKO LEJE 02";"618"']
['93257;2025-06-04 22:00:00', '000;"SÅRSKIFT";"Nej";"Nej";"";103;"Nej";"CKO LEJE 02";"618"']
['94086;2025-06-11 10:45:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";85;"Nej";"CKO RTG LEJE 11";"618"']
['94730;2025-06-14 11:00:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";89;"Nej";"CKO LEJE 04";"618"']
['94805;2025-06-16 12:50:00', '000;"NEFROSTOMI";"Nej";"Nej";"";68;"Nej";"CKO LEJE 05";"618"']
['94961;2025-06-18 08:05:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";86;"Nej";"CKO RTG LEJE 11";"618"']
['95426;2025-06-19 13:03:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";96;"Nej";"CKO LEJE 04";"618"']
['95608;2025-06-19 15:40:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";104;"Nej";"CKO RTG LEJE 11";"618"']
['95839;2025-06-20 10:30:00', '000;"INVR VENOGRAFI THORAX";"Nej";"Nej";"";116;"Nej";"CKO RTG LEJE 12";"618"']
['96192;2025-06-23 18:00:00', '000;"REOPERATION ABDOMINALKIRURGI - SÅRRUPTUR";"Nej";"Nej";"";111;"Nej";"CKO LEJE 02";"618"']
['96992;2025-06-26 15:20:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";95;"Nej";"CKO RTG LEJE 14";"618"']
['98250;2025-07-04 08:00:00', '000;"INVR VENOGRAFI ABDOMEN";"Nej";"Nej";"";138;"Nej";"CKO RTG LEJE 12";"618"']
['99153;2025-07-11 18:00:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";98;"Nej";"CKO LEJE 03";"618"']
['100380;2025-07-22 08:10:00', '000;"INVR CHOLANGIOGRAFI";"Nej";"Nej";"";104;"Nej";"CKO RTG LEJE 12";"618"']
['100661;2025-07-23 17:30:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";104;"Nej";"CKO LEJE 03";"618"']
['100723;2025-07-26 12:40:00', '000;"GASTROSKOPI";"Nej";"Nej";"";23;"Nej";"CKO LEJE 01";"618"']
['101083;2025-07-28 10:30:00', '000;"INVR ANGIOGRAFI ABDOMEN";"Nej";"Nej";"";169;"Nej";"CKO RTG LEJE 12";"618"']
['101149;2025-07-28 18:10:00', '000;"NEFROSTOMI";"Nej";"Nej";"";80;"Nej";"CKO LEJE 04";"618"']
['101200;2025-07-29 14:00:00', '000;"JJ-KATETER ANLÆGGELSE";"Nej";"Nej";"";98;"Nej";"CKO LEJE 03";"618"']
['101651;2025-08-02 09:00:00', '000;"PTA PTRA ANGIO";"Nej";"Nej";"";156;"Nej";"CKO KAR 2 (H) (3032)";"618"']
['102888;2025-09-10 08:00:00', '000;"ÅBEN ADRENALEKTOMI";"Nej";"Nej";"";263;"Nej";"CKO LEJE 04";"618"']
['103950;2025-08-19 18:00:00', '000;"SÅRSKIFT";"Nej";"Nej";"";108;"Nej";"CKO LEJE 02";"618"']
['104134;2025-08-22 16:05:00', '000;"SÅRSKIFT";"Nej";"Nej";"";105;"Nej";"CKO LEJE 02";"618"']
['104455;2025-08-22 10:24:00', '000;"NEFROSTOMI";"Nej";"Nej";"";96;"Nej";"CKO LEJE 04";"618"']
['104781;2025-08-24 09:00:00', '000;"VAC-BEHANDLING";"Nej";"Nej";"";109;"Nej";"CKO LEJE 02";"618"']
['104782;2025-08-23 16:00:00', '000;"GASTROSKOPI";"Nej";"Nej";"";54;"Nej";"CKO LEJE 01";"618"']
['105220;2025-08-26 20:10:00', '000;"REOPERATION ABDOMINALKIRURGI - FASCIERUPTUR";"Nej";"Nej";"";121;"Nej";"CKO LEJE 02";"618"']
['107365;2025-09-10 09:00:00', '000;"EKSPLORATIV LAPAROTOMI";"Nej";"Nej";"";196;"Nej";"CKO LEJE 01";"618"']
['108546;2025-09-16 16:05:00', '000;"REOPERATION ABDOMINALKIRURGI - SÅRRUPTUR";"Nej";"Nej";"";93;"Nej";"CKO LEJE 01";"618"']
['108683;2025-09-18 16:35:00', '000;"SÅRSKIFT";"Nej";"Nej";"";99;"Nej";"CKO LEJE 03";"618"']
['108876;2025-09-17 20:15:00', '000;"NEFROSTOMI";"Nej";"Nej";"";72;"Nej";"CKO LEJE 04";"618"']
['113100;2025-10-15 20:05:00', '000;"NEFROSTOMI";"Nej";"Nej";"";61;"Nej";"CKO LEJE 04";"618"']
['113176;2025-10-17 08:25:00', '000;"PTA UE ANGIO";"Nej";"Nej";"";97;"Nej";"CKO KAR 2 (H) (3032)";"618"']

In [2]:
df_cancelled = pd.read_csv("../Data and descriptions/Case Rigshospitalet - Cancelled operations.csv", sep=';')
df_complete = pd.read_csv("../Data and descriptions/Case Rigshospitalet - Completed operations.csv", sep = ';')

C:\Users\frida\AppData\Local\Temp\ipykernel_30200\3600004165.py:2: DtypeWarning: Columns (13,14,21,22,23,24,25,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df_complete = pd.read_csv("../Data and descriptions/Case Rigshospitalet - Completed operations.csv", sep = ';')

In [3]:
# remove columns with staff and resources
df_complete_wo = df_complete.drop(columns=[col for col in df_complete.columns if col.startswith("Ressource")])
df_complete_wo = df_complete_wo.drop(columns=[col for col in df_complete_wo.columns if col.startswith("Staff")])
#df_complete_wo.describe()

In [4]:
df_complete_wo = df_complete_wo.drop(columns=['Forsinkelsesårsag'])

In [5]:
datetime_variables = ['Dato', 'Pt ankommet til hospitalet', 'Planlagt stue klargøring start', 'Planlagt stue klargøring start', 'Stue klargøring start', 'Stue klargjort', 'Patient på stuen', 'Patient på stuen (Planlagt)', 'Procedure start', 'Procedure slut', 'Patient klar til afgang', 'Patient forlader stuen (Planlagt)', 'Patient forlader stuen', 'Stue rengjort (Planlagt)', 'Stue rengøring start', 'Stue rengjort', 'Patient forlader afdeling']
# Make datetime objects
for i in datetime_variables:
    df_complete_wo[i] = pd.to_datetime(df_complete_wo[i], format='%Y-%m-%d %H:%M:%S,%f')

In [6]:
# Make datetime objects
for i in datetime_variables:
    df_complete_wo[i] = pd.to_datetime(df_complete_wo[i], format='%Y-%m-%d %H:%M:%S,%f')

In [7]:
df_complete_wo['Overskredet (minutter)'].max()

1560.0

In [8]:
df_complete_wo['Forsinkelse (minutter)'].max()

1585.0

In [9]:
df_no_outliers = df_complete_wo[(df_complete_wo['Forsinkelse (minutter)'] >= -300) & 
                  (df_complete_wo['Forsinkelse (minutter)'] <= 300)].copy()

In [10]:
# Udtræk 'Time på dagen' og 'Ugedag'
df_no_outliers['Time'] = df_no_outliers['Procedure start'].dt.hour
df_no_outliers['Ugedag'] = df_no_outliers['Procedure start'].dt.day_name()

# Sorter ugedage så de ikke står alfabetisk
dage_orden = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
df_no_outliers['Ugedag'] = pd.Categorical(df_no_outliers['Ugedag'], categories=dage_orden, ordered=True)

In [11]:
op_talt_per_time = df_no_outliers[df_no_outliers['Akut case (J/N)'] == 'Nej']['Time'].value_counts().sort_index()
print("Antal planlagte operationer per time:")
print(op_talt_per_time)

Antal planlagte operationer per time:
Time
0.0         2
1.0         6
2.0         1
3.0         2
7.0         2
8.0     14750
9.0     26579
10.0    16149
11.0    14654
12.0    13015
13.0    12658
14.0     5792
15.0     1037
16.0      603
17.0      304
18.0      115
19.0       68
20.0       65
21.0       34
22.0       22
23.0        9
Name: count, dtype: int64

In [12]:
df_no_outliers.columns

Index(['Case-ID Anonymous', 'Patient Alder', 'Speciale', 'Stue',
       'Operationsgang ID', 'Akut case (J/N)', 'Dato',
       'Pt ankommet til hospitalet', 'Planlagt stue klargøring start',
       'Stue klargøring start', 'Stue klargjort',
       'Patient på stuen (Planlagt)', 'Patient på stuen', 'Anæstesistart',
       'Anæstesi melder klar', 'Procedure start', 'Procedure slut',
       'Patient klar til afgang', 'Patient forlader stuen (Planlagt)',
       'Patient forlader stuen', 'Stue rengjort (Planlagt)',
       'Stue rengøring start', 'Stue rengjort', 'I opvågning', 'Anæstesistop',
       'Klar til udskrivelse efter opvågning', 'Patient forlader afdeling',
       'Forsinkelse (minutter)', 'Overskredet (minutter)',
       'Procedure - Tekst & ID', 'Aktionsdiagnose - Kode & tekst',
       'Aktionsdiagnose - Gruppe', 'Time', 'Ugedag'],
      dtype='object')

In [13]:

df_eye = df_no_outliers[df_no_outliers['Speciale'] == 'Øjenkirurgi'].copy()

# Faktisk Varighed
df_eye['Faktisk_Varighed'] = (df_eye['Patient forlader stuen'] - df_eye['Patient på stuen']).dt.total_seconds() / 60

# Planlagt Varighed
# Vi bruger 'Patient forlader stuen (Planlagt)' og 'Patient på stuen (Planlagt)' 
# for at se, hvad der var afsat til hele seancen
df_eye['Planlagt_Varighed'] = (df_eye['Patient forlader stuen (Planlagt)'] - df_eye['Patient på stuen (Planlagt)']).dt.total_seconds() / 60

# Afvigelse
# Positiv værdi - Operationen tog længere tid 
# Negativ værdi - Operationen tog kortere tid
df_eye['Varighed_Afvigelse'] = df_eye['Faktisk_Varighed'] - df_eye['Planlagt_Varighed']

In [46]:
df_eye['Afvigelse2'] = df_eye['Overskredet (minutter)'] - df_eye['Forsinkelse (minutter)']

In [14]:
df_eye['Klargøring_afvigelse'] = (df_eye['Stue klargøring start'] - df_eye['Planlagt stue klargøring start']).dt.total_seconds() / 60

In [47]:
df_eye.columns

Index(['Case-ID Anonymous', 'Patient Alder', 'Speciale', 'Stue',
       'Operationsgang ID', 'Akut case (J/N)', 'Dato',
       'Pt ankommet til hospitalet', 'Planlagt stue klargøring start',
       'Stue klargøring start', 'Stue klargjort',
       'Patient på stuen (Planlagt)', 'Patient på stuen', 'Anæstesistart',
       'Anæstesi melder klar', 'Procedure start', 'Procedure slut',
       'Patient klar til afgang', 'Patient forlader stuen (Planlagt)',
       'Patient forlader stuen', 'Stue rengjort (Planlagt)',
       'Stue rengøring start', 'Stue rengjort', 'I opvågning', 'Anæstesistop',
       'Klar til udskrivelse efter opvågning', 'Patient forlader afdeling',
       'Forsinkelse (minutter)', 'Overskredet (minutter)',
       'Procedure - Tekst & ID', 'Aktionsdiagnose - Kode & tekst',
       'Aktionsdiagnose - Gruppe', 'Time', 'Ugedag', 'Faktisk_Varighed',
       'Planlagt_Varighed', 'Varighed_Afvigelse', 'Klargøring_afvigelse',
       'Afvigelse2'],
      dtype='object')

In [60]:
df_eye[['Patient på stuen (Planlagt)', 'Procedure start', 'Patient på stuen']]

       Patient på stuen (Planlagt)     Procedure start    Patient på stuen
28             2024-10-22 11:30:00 2024-10-22 11:45:00 2024-10-22 11:33:00
39             2024-01-16 12:15:00 2024-01-16 13:02:00 2024-01-16 12:52:00
44             2024-01-24 13:00:00 2024-01-24 13:05:00 2024-01-24 12:50:00
58             2024-06-05 12:30:00 2024-06-05 13:35:00 2024-06-05 13:29:00
59             2024-06-05 12:30:00 2024-06-05 13:35:00 2024-06-05 13:29:00
...                            ...                 ...                 ...
133153         2025-12-18 12:30:00 2025-12-18 13:22:00 2025-12-18 13:17:00
133154         2025-12-23 11:00:00 2025-12-23 11:40:00 2025-12-23 11:35:00
133155         2025-12-19 11:00:00 2025-12-19 11:56:00 2025-12-19 11:52:00
133156         2025-12-22 08:30:00 2025-12-22 09:19:00 2025-12-22 09:12:00
133157         2025-12-19 09:45:00 2025-12-19 10:50:00 2025-12-19 10:43:00

[40824 rows x 3 columns]

# Nye ting

In [51]:
# 2. Beregn varigheden i minutter
df_eye['Faktisk_klargøringstid'] = (df_eye['Stue klargjort'] - df_eye['Stue klargøring start']).dt.total_seconds() / 60

# 3. Se gennemsnittet
gns_klargøring = df_eye['Faktisk_klargøringstid'].mean()
median_klargøring = df_eye['Faktisk_klargøringstid'].median()

print(f"Gennemsnitlig klargøringstid: {gns_klargøring:.2f} minutter")
print(f"Median klargøringstid: {median_klargøring:.2f} minutter")

Gennemsnitlig klargøringstid: 1.71 minutter
Median klargøringstid: 0.00 minutter

In [61]:
# Filtrer så vi kun ser på rækker med logiske tidsintervaller (f.eks. mellem 1 min og 120 min)
rensede_data_klargøring = df_eye[df_eye['Faktisk_klargøringstid'] > 0]['Faktisk_klargøringstid']
rensede_data_rengøring = df_eye[df_eye['Faktisk_rengøringstid'] > 0]['Faktisk_rengøringstid']

print(f" gns. klargøring: {rensede_data_klargøring.mean():.2f} min")
print(f" gns. rengøring: {rensede_data_rengøring.mean():.2f} min")

 gns. klargøring: 9.24 min
 gns. rengøring: 9.50 min

In [59]:
antal_negative = (df_eye['Faktisk_klargøringstid'] < 0).sum()
antal_negative

antal_ialt = (df_eye['Faktisk_klargøringstid']).sum()
antal_ialt

69628.0

In [54]:
# Beregn faktisk rengøringstid
df_eye['Faktisk_rengøringstid'] = (df_eye['Stue rengjort'] - df_eye['Stue rengøring start']).dt.total_seconds() / 60

# 3. Se gennemsnittet
gns_klargøring = df_eye['Faktisk_rengøringstid'].mean()
median_klargøring = df_eye['Faktisk_rengøringstid'].median()

print(f"Gennemsnitlig rengøringstid: {gns_klargøring:.2f} minutter")
print(f"Median rengøringstid: {median_klargøring:.2f} minutter")

Gennemsnitlig rengøringstid: 0.71 minutter
Median rengøringstid: 0.00 minutter

In [48]:
# Hvor stor en del af forsinkelsen skyldes klargøring vs. selve proceduren?
print(df_eye[['Klargøring_afvigelse', 'Varighed_Afvigelse', 'Forsinkelse (minutter)']].describe())

# Se korrelationen - hvad hænger stærkest sammen med 'Forsinkelse (minutter)'?
print(df_eye[['Afvigelse2', 'Klargøring_afvigelse', 'Varighed_Afvigelse', 'Forsinkelse (minutter)']].corr())

       Klargøring_afvigelse  Varighed_Afvigelse  Forsinkelse (minutter)
count          40762.000000        40823.000000            40824.000000
mean              33.153035            4.350440               41.006026
std               39.338249           18.017114               36.797693
min            -1423.000000         -146.000000             -274.000000
25%               10.000000           -2.000000               20.000000
50%               33.000000            3.000000               39.000000
75%               55.000000           10.000000               60.000000
max              291.000000          514.000000              299.000000
                        Afvigelse2  Klargøring_afvigelse  Varighed_Afvigelse  \
Afvigelse2                1.000000              0.012779            1.000000
Klargøring_afvigelse      0.012779              1.000000            0.012779
Varighed_Afvigelse        1.000000              0.012779            1.000000
Forsinkelse (minutter)    0.016862              0.929423            0.016862

                        Forsinkelse (minutter)
Afvigelse2                            0.016862
Klargøring_afvigelse                  0.929423
Varighed_Afvigelse                    0.016862
Forsinkelse (minutter)                1.000000

In [16]:

# timerne fra 7 til og med 22
df_filtered = df_eye[(df_eye['Time'] >= 7) & (df_eye['Time'] <= 22)]

# 2. Lav den gennemsnitlige beregning baseret på det filtrerede data
pivot_data = df_filtered.groupby('Time')[['Forsinkelse (minutter)', 'Varighed_Afvigelse', 'Klargøring_afvigelse']].mean().reset_index()

# 3. Lav plottet
fig = px.line(pivot_data, x='Time', y=['Forsinkelse (minutter)', 'Varighed_Afvigelse', 'Klargøring_afvigelse'],
              title='Forsinkelse vs. Operationseffektivitet (Kl. 07-22)',
              labels={'value': 'Minutter', 'Time': 'Time på dagen'},
              markers=True,
              template="plotly_white")

# Gør x-aksen pænere, så den viser hver time
fig.update_layout(xaxis=dict(tickmode='linear', tick0=7, dtick=1))

fig.show()

In [17]:

# Faktisk Varighed
df_no_outliers['Faktisk_Varighed'] = (df_no_outliers['Patient forlader stuen'] - df_no_outliers['Patient på stuen']).dt.total_seconds() / 60

# Planlagt Varighed
# Vi bruger 'Patient forlader stuen (Planlagt)' og 'Patient på stuen (Planlagt)' 
# for at se, hvad der var afsat til hele seancen
df_no_outliers['Planlagt_Varighed'] = (df_no_outliers['Patient forlader stuen (Planlagt)'] - df_no_outliers['Patient på stuen (Planlagt)']).dt.total_seconds() / 60

# Afvigelse
# Positiv værdi - Operationen tog længere tid 
# Negativ værdi - Operationen tog kortere tid
df_no_outliers['Varighed_Afvigelse'] = df_no_outliers['Faktisk_Varighed'] - df_no_outliers['Planlagt_Varighed']

In [18]:
df_no_outliers['Klargøring_afvigelse'] = (df_no_outliers['Stue klargøring start'] - df_no_outliers['Planlagt stue klargøring start']).dt.total_seconds() / 60

In [19]:

# forsinkelse indrul
df_no_outliers['Forsinkelse_indrul'] = (df_no_outliers['Patient på stuen'] - df_no_outliers['Stue klargjort']).dt.total_seconds() / 60

In [20]:

# timerne fra 7 til og med 22
df_filtered = df_no_outliers[(df_no_outliers['Time'] >= 7) & (df_no_outliers['Time'] <= 22)]

# 2. Lav den gennemsnitlige beregning baseret på det filtrerede data
pivot_data = df_filtered.groupby('Time')[['Forsinkelse (minutter)', 'Varighed_Afvigelse', 'Klargøring_afvigelse', 'Forsinkelse_indrul']].mean().reset_index()

# 3. Lav plottet
fig = px.line(pivot_data, x='Time', y=['Forsinkelse (minutter)', 'Varighed_Afvigelse', 'Klargøring_afvigelse', 'Forsinkelse_indrul'],
              title='Forsinkelse vs. Operationseffektivitet (Kl. 07-22)',
              labels={'value': 'Minutter', 'Time': 'Time på dagen'},
              markers=True,
              template="plotly_white")

# Gør x-aksen pænere, så den viser hver time
fig.update_layout(xaxis=dict(tickmode='linear', tick0=7, dtick=1))

fig.show()

In [21]:
df_planlagt = df_no_outliers[df_no_outliers['Akut case (J/N)'] == 'Nej'].copy()

In [22]:

# timerne fra 7 til og med 22
df_filtered = df_planlagt[(df_planlagt['Time'] >= 8) & (df_planlagt['Time'] <= 22)]

# 2. Lav den gennemsnitlige beregning baseret på det filtrerede data
pivot_data = df_filtered.groupby('Time')[['Forsinkelse (minutter)', 'Varighed_Afvigelse', 'Klargøring_afvigelse', 'Forsinkelse_indrul']].mean().reset_index()

# 3. Lav plottet
fig = px.line(pivot_data, x='Time', y=['Forsinkelse (minutter)', 'Varighed_Afvigelse', 'Klargøring_afvigelse', 'Forsinkelse_indrul'],
              title='Forsinkelse vs. Operationseffektivitet (Kl. 07-22)',
              labels={'value': 'Minutter', 'Time': 'Time på dagen'},
              markers=True,
              template="plotly_white")

# Gør x-aksen pænere, så den viser hver time
fig.update_layout(xaxis=dict(tickmode='linear', tick0=7, dtick=1))

fig.show()

In [23]:
df_planlagt['Stue']

0         OPNORD 23.240 (H)
1         OPNORD 13.114 (H)
2         OPNORD 13.114 (H)
3         OPNORD 13.110 (H)
4                OPNORD 301
                ...
133153     GLO Ø 46 STUE 07
133154     GLO Ø 46 STUE 07
133155     GLO Ø 36 STUE 05
133156     GLO Ø 36 STUE 05
133157            GLO VB 10
Name: Stue, Length: 106026, dtype: object

In [24]:
df_planlagt_eye = df_eye[df_eye['Akut case (J/N)'] == 'Nej'].copy()

In [25]:

# timerne fra 7 til og med 22
df_filtered = df_planlagt_eye[(df_planlagt_eye['Time'] >= 8) & (df_planlagt_eye['Time'] <= 22)]

# 2. Lav den gennemsnitlige beregning baseret på det filtrerede data
pivot_data = df_filtered.groupby('Time')[['Forsinkelse (minutter)', 'Varighed_Afvigelse', 'Klargøring_afvigelse']].mean().reset_index()

# 3. Lav plottet
fig = px.line(pivot_data, x='Time', y=['Forsinkelse (minutter)', 'Varighed_Afvigelse', 'Klargøring_afvigelse'],
              title='Forsinkelse vs. Operationseffektivitet (Kl. 07-22)',
              labels={'value': 'Minutter', 'Time': 'Time på dagen'},
              markers=True,
              template="plotly_white")

# Gør x-aksen pænere, så den viser hver time
fig.update_layout(xaxis=dict(tickmode='linear', tick0=7, dtick=1))

fig.show()

In [44]:
df_planlagt_eye

,Case-ID Anonymous,Patient Alder,Speciale,Stue,Operationsgang ID,Akut case (J/N),Dato,Pt ankommet til hospitalet,Planlagt stue klargøring start,Stue klargøring start,...,Overskredet (minutter),Procedure - Tekst & ID,Aktionsdiagnose - Kode & tekst,Aktionsdiagnose - Gruppe,Time,Ugedag,Faktisk_Varighed,Planlagt_Varighed,Varighed_Afvigelse,Klargøring_afvigelse
28,271,85,Øjenkirurgi,GLO Ø 36 STUE 01,625,Nej,2024-10-22,2024-10-22 10:11:00,2024-10-22 11:30:00,2024-10-22 11:31:00,...,2.0,"PTOSE, LEVATORKIRURGI - LA [1070010580]",DH024: Blefaroptose,"Sygdomme i øjenlåg, tårekirtel og øjenhule",11.0,Tuesday,59.0,60.0,-1.0,1.0
39,349,68,Øjenkirurgi,GLO Ø 36 STUE 01,625,Nej,2024-01-16,2024-01-16 11:57:00,2024-01-16 12:15:00,2024-01-16 12:43:00,...,45.0,"EKTROPION MED RETRAKTOR-, MEDIAL-, OG LATERAL...",DH109: Konjunktivitis UNS,Sygdomme i øjets bindehinde,13.0,Tuesday,63.0,55.0,8.0,28.0
44,449,74,Øjenkirurgi,GLO Ø 36 STUE 03,625,Nej,2024-01-24,2024-01-24 10:02:00,2024-01-24 13:00:00,2024-01-24 12:45:00,...,21.0,"BLEPHAROPLASTIK, ØVRE BILATERAL - LA [1070010466]",DH024: Blefaroptose,"Sygdomme i øjenlåg, tårekirtel og øjenhule",13.0,Wednesday,81.0,50.0,31.0,-15.0
58,476,75,Øjenkirurgi,GLO Ø 36 STUE 01,625,Nej,2024-06-05,2024-06-05 12:10:00,2024-06-05 12:30:00,2024-06-05 13:28:00,...,71.0,"INTUBATION AF TÅREKANAL TIL TÅRESÆK, UNILATERA...",DH042: Epifora,"Sygdomme i øjenlåg, tårekirtel og øjenhule",13.0,Wednesday,40.0,28.0,12.0,58.0
59,476,75,Øjenkirurgi,GLO Ø 36 STUE 01,625,Nej,2024-06-05,2024-06-05 12:10:00,2024-06-05 12:30:00,2024-06-05 13:28:00,...,71.0,"SONDERING AF TÅREKANAL, BILATERAL - LA [107001...",DH042: Epifora,"Sygdomme i øjenlåg, tårekirtel og øjenhule",13.0,Wednesday,40.0,28.0,12.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133153,120283,59,Øjenkirurgi,GLO Ø 46 STUE 07,625,Nej,2025-12-18,2025-12-18 12:09:00,2025-12-18 12:30:00,2025-12-18 13:13:00,...,51.0,FAKO 2 - LA [1070010663],DH259: Aldersbetinget grå stær (>=50 år) UNS,Sygdomme i øjets linse,13.0,Thursday,19.0,15.0,4.0,43.0
133154,120284,58,Øjenkirurgi,GLO Ø 46 STUE 07,625,Nej,2025-12-23,2025-12-23 10:50:00,2025-12-23 11:00:00,2025-12-23 11:32:00,...,40.0,FAKO 3 - LA [1070010664],DH259: Aldersbetinget grå stær (>=50 år) UNS,Sygdomme i øjets linse,11.0,Tuesday,20.0,15.0,5.0,32.0
133155,120291,70,Øjenkirurgi,GLO Ø 36 STUE 05,625,Nej,2025-12-19,2025-12-19 10:39:00,2025-12-19 11:00:00,2025-12-19 11:52:00,...,52.0,FAKO 3 - LA [1070010664],DH259: Aldersbetinget grå stær (>=50 år) UNS,Sygdomme i øjets linse,11.0,Friday,15.0,15.0,0.0,52.0
133156,120337,87,Øjenkirurgi,GLO Ø 36 STUE 05,625,Nej,2025-12-22,2025-12-22 08:17:00,2025-12-22 08:30:00,2025-12-22 09:04:00,...,50.0,FAKO - LA BILATERAL [1070015679],DH259: Aldersbetinget grå stær (>=50 år) UNS,Sygdomme i øjets linse,9.0,Monday,38.0,30.0,8.0,34.0
133157,120370,63,Øjenkirurgi,GLO VB 10,625,Nej,2025-12-19,2025-12-19 09:28:00,2025-12-19 09:45:00,2025-12-19 10:39:00,...,70.0,FAKO - LA BILATERAL [1070015679],DH259: Aldersbetinget grå stær (>=50 år) UNS,Sygdomme i øjets linse,10.0,Friday,42.0,30.0,12.0,54.0

In [43]:
df_planlagt_eye[['Planlagt stue klargøring start', 'Stue klargøring start', 'Procedure start', 'Stue rengjort (Planlagt)', 'Stue rengjort']]

,Planlagt stue klargøring start,Stue klargøring start,Procedure start,Stue rengjort (Planlagt),Stue rengjort
28,2024-10-22 11:30:00,2024-10-22 11:31:00,2024-10-22 11:45:00,2024-10-22 12:30:00,NaT
39,2024-01-16 12:15:00,2024-01-16 12:43:00,2024-01-16 13:02:00,2024-01-16 13:10:00,NaT
44,2024-01-24 13:00:00,2024-01-24 12:45:00,2024-01-24 13:05:00,2024-01-24 13:50:00,NaT
58,2024-06-05 12:30:00,2024-06-05 13:28:00,2024-06-05 13:35:00,2024-06-05 12:58:00,NaT
59,2024-06-05 12:30:00,2024-06-05 13:28:00,2024-06-05 13:35:00,2024-06-05 12:58:00,NaT
...,...,...,...,...,...
133153,2025-12-18 12:30:00,2025-12-18 13:13:00,2025-12-18 13:22:00,2025-12-18 12:45:00,2025-12-18 13:38:00
133154,2025-12-23 11:00:00,2025-12-23 11:32:00,2025-12-23 11:40:00,2025-12-23 11:15:00,2025-12-23 11:55:00
133155,2025-12-19 11:00:00,2025-12-19 11:52:00,2025-12-19 11:56:00,2025-12-19 11:15:00,2025-12-19 12:07:00
133156,2025-12-22 08:30:00,2025-12-22 09:04:00,2025-12-22 09:19:00,2025-12-22 09:00:00,2025-12-22 09:52:00
133157,2025-12-19 09:45:00,2025-12-19 10:39:00,2025-12-19 10:50:00,2025-12-19 10:15:00,2025-12-19 11:25:00

In [26]:
# Giver dig både min, max, gennemsnit og median for kl. 8
print(df_planlagt[df_planlagt['Time'] == 8]['Forsinkelse (minutter)'].describe())

count    14750.000000
mean        10.951186
std         20.318120
min       -299.000000
25%          2.000000
50%          9.000000
75%         22.000000
max        159.000000
Name: Forsinkelse (minutter), dtype: float64

In [27]:
# 1. Definer hvilken stue du vil se på (kopier navnet præcis fra dine data)
valgt_stue = 'GLO Ø 46 STUE 07' 

# 2. Filtrer for både tid OG den specifikke stue
df_filtered = df_planlagt[
    (df_planlagt['Time'] >= 8) & 
    (df_planlagt['Time'] <= 22) & 
    (df_planlagt['Stue'] == valgt_stue)
]

# 3. Lav den gennemsnitlige beregning (samme som før)
pivot_data = df_filtered.groupby('Time')[['Forsinkelse (minutter)', 'Varighed_Afvigelse', 'Klargøring_afvigelse', 'Forsinkelse_indrul']].mean().reset_index()

# 4. Lav plottet (opdateret titel så man kan se hvilken stue det er)
fig = px.line(pivot_data, x='Time', y=['Forsinkelse (minutter)', 'Varighed_Afvigelse', 'Klargøring_afvigelse', 'Forsinkelse_indrul'],
              title=f'Forsinkelse og afvigelser for {valgt_stue}',
              labels={'value': 'Minutter', 'Time': 'Time på dagen'},
              markers=True,
              template="plotly_white")

fig.update_layout(xaxis=dict(tickmode='linear', tick0=8, dtick=1))

fig.show()

In [28]:
# 1. Vælg den stue du vil undersøge
valgt_stue = 'GLO Ø 46 STUE 07'

# 2. Filtrer for både kl. 8 OG den specifikke stue
stats_kl8_stue = df_planlagt[
    (df_planlagt['Time'] == 8) & 
    (df_planlagt['Stue'] == valgt_stue)
]['Forsinkelse (minutter)'].describe()

print(f"Statistik for {valgt_stue} kl. 08:00:")
print(stats_kl8_stue)

Statistik for GLO Ø 46 STUE 07 kl. 08:00:
count    283.000000
mean      32.261484
std       10.807905
min      -65.000000
25%       31.000000
50%       34.000000
75%       37.000000
max       56.000000
Name: Forsinkelse (minutter), dtype: float64

In [29]:
df_planlagt['Stue'].unique()

array(['OPNORD 23.240 (H)', 'OPNORD 13.114 (H)', 'OPNORD 13.110 (H)',
       'OPNORD 301', 'RH TMK AMB 1', 'RH TMK AMB 2', 'OPNORD 13.109 (H)',
       'RH DAGKIR A (H)', 'OPNORD 302', 'RH DAGKIR D (H)',
       'GLO Ø 36 STUE 01', 'OPNORD 13.111 (H)', 'OPNORD 303',
       'GLO Ø 36 STUE 03', 'RH TMK AMB 3', 'GLO Ø 36 STUE 02',
       'OPNORD 13.116 (H)', 'OPNORD 13.106 (H)', 'RH TMK AMB 4',
       'RH DAGKIR B (H)', 'GLO VB 16', 'OPNORD 13.115 (H)',
       'RH DAGKIR C (H)', 'RH TMK AMB 5', 'GLO VB 14', 'RH DAGKIR E (H)',
       'GLO VB 15', 'CKO 3111', 'GLO Ø 46 STUE 09', 'GLO Ø 36 STUE 04',
       'GLO Ø 36 STUE 05', 'CKO LEJE 05', 'RT GN', 'GLO MB 08',
       'AMBULANT OPERATION 8067', 'GLO Ø 46 STUE 11',
       'CKO TRAUME RTG LEJE 13', 'GLO Ø 46 STUE 10', 'OPNORD 13.113 (H)',
       'OPNORD 23.244 (H)', 'OPNORD 13.105 (H)', 'GLO VB 10',
       'GLO Ø 46 STUE 07', 'OPNORD 13.112 (H)', 'CKO LEJE 04',
       'GLO Ø 46 STUE 08', 'OPNORD 13.103 (H)', 'CKO LEJE 03',
       'GLO Ø SEC-HK', 'OPNORD 23.238 (H)', 'OPNORD 23.241 (H)',
       'GLO MB 09', 'OPNORD 23.246 (H)', 'OPNORD 13.101 (H)',
       'OPNORD 13.102 (H)', 'GLO VB 11', 'CKO KAR 1 (H) (3032)',
       'OPNORD 23.236 (H)', 'OPNORD 23.245 (H)', 'OPNORD 23.233 (H)',
       'OPNORD 13.108 (H)', 'JMC 05', 'RT LEJE 11', 'GLO ØB 03',
       'OPNORD 23.248 (H)', 'OPNORD 13.107 (H)', 'CKO RTG LEJE 12',
       'RT ENDO 3151', 'JMC 09', 'OPNORD 23.242 (H)', 'CKO RTG LEJE 11',
       'CKO RTG LEJE 14', 'CKO RTG LEJE U/A', 'GLO ØB 05', 'GLO ØB 06',
       'GLO ØB 01', 'GLO ØB 07', 'GLO ØB 02', 'GLO ØB 04',
       'CKO KAR 2 (H) (3032)', 'CKO LEJE 16', 'OPNORD 23.243 (H)',
       'OPNORD 23.237 (H)', 'OPNORD 23.247 (H)', 'OPNORD 23.239 (H)',
       'CKO LEJE 17', 'CKO LEJE 01', 'CKO LEJE 02', 'CKO LEJE 06',
       'CKO LEJE 21', 'OPNORD 13.104 (H)', 'JMC 07', 'RT LEJE 15',
       'RT LEJE 13', 'RT LEJE 07', 'OPNORD 23.234 (H)', 'RT LEJE 14',
       'RT LEJE 20', 'RT LEJE 23', 'RT LEJE 12', 'RT LEJE 09, 3041 (H)',
       'CKO LEJE 08 (H)', 'JMC X', 'JMC 08', 'JMC 04',
       'OPNORD 13.117 (H)', 'JMC Y', 'JMC 02', 'OPNORD 13.118 (H)',
       'CKO LEJE 18', 'CKO LEJE 22', 'OPNORD ANGIO 23.232 (H)', 'JMC 06',
       'JMC 03', 'GLO VB 13', 'RT LEJE 19', 'JMC 01',
       'RH  VIRTUELT LEJE, SKAL OMDØBES', 'OPNORD 484 (H)',
       'RH CKO HUGO (7023) (H)', 'OPNORD ANGIO 23.231 (H)', 'GLO VB 12',
       'JMC UDE-ANÆSTESI', 'JMC 10 (3034) (H)'], dtype=object)

In [30]:
# 1. Lav en liste til at gemme resultaterne
stuer_med_positiv_min = []

# 2. Gå igennem alle unikke stuer
for stue in df_planlagt['Stue'].unique():
    # Filtrer data for den specifikke stue kl. 8
    subset = df_planlagt[(df_planlagt['Stue'] == stue) & (df_planlagt['Time'] == 8)]
    
    # Tjek om der overhovedet er data for denne stue kl. 8
    if not subset.empty:
        min_forsinkelse = subset['Forsinkelse (minutter)'].min()
        
        # 3. Gem stuen, hvis minimumsforsinkelsen er større end 0
        if min_forsinkelse > 0:
            stuer_med_positiv_min.append({
                'Stue': stue,
                'Min_Forsinkelse': min_forsinkelse,
                'Gennemsnit': subset['Forsinkelse (minutter)'].mean(),
                'Antal_Operationer': len(subset)
            })

# 4. Lav resultatet om til en DataFrame så det er nemt at læse
df_problem_stuer = pd.DataFrame(stuer_med_positiv_min)

# Sorter så dem med den højeste minimumsforsinkelse står øverst
if not df_problem_stuer.empty:
    df_problem_stuer = df_problem_stuer.sort_values(by='Min_Forsinkelse', ascending=False)
    print("Stuer hvor ALLE operationer kl. 08:00 er forsinkede:")
    print(df_problem_stuer)
else:
    print("Ingen stuer har en minimumsforsinkelse over 0.")

Stuer hvor ALLE operationer kl. 08:00 er forsinkede:
                      Stue  Min_Forsinkelse  Gennemsnit  Antal_Operationer
2             GLO Ø SEC-HK             20.0   31.705882                 17
0             RH TMK AMB 2              7.0   12.000000                  4
1             RH TMK AMB 3              6.0   13.666667                  3
4              CKO LEJE 18              3.0    7.166667                  6
5  OPNORD ANGIO 23.231 (H)              2.0    3.666667                  3
3        OPNORD 13.108 (H)              1.0    4.250000                  4